# Deploy/docker/docker-compose.yml
version: "3"

services:
  player-service:
    image: vfiftyfive/oda-playerservice:latest
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/oda
    depends_on:
      - db
    entrypoint: ["/app/wait-for-it.sh", "db:5432", --, "/app/playerservice"]

  case-service:
    image: vfiftyfive/oda-caseservice:latest
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/oda
    depends_on:
      - db
    entrypoint: ["/app/wait-for-it.sh", "db:5432", --, "/app/caseservice"]

  evidence-service:
    image: vfiftyfive/oda-evidenceservice:latest
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/oda
    depends_on:
      - db
    entrypoint: ["/app/wait-for-it.sh", "db:5432", --, "/app/evidenceservice"]

  interrogation-service:
    image: vfiftyfive/oda-interrogationservice:latest
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/oda
    depends_on:
      - db
    entrypoint:
      ["/app/wait-for-it.sh", "db:5432", --, "/app/interrogationservice"]

  deduction-service:
    image: vfiftyfive/oda-deductionservice:latest
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/oda
    depends_on:
      - db
    entrypoint: ["/app/wait-for-it.sh", "db:5432", --, "/app/deductionservice"]

  csi-service:
    image: vfiftyfive/oda-csiservice:latest
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/oda
    depends_on:
      - db
    entrypoint: ["/app/wait-for-it.sh", "db:5432", --, "/app/csiservice"]

  game-service:
    image: vfiftyfive/oda-gameservice:latest
    ports:
      - "8080:8080"
    environment:
      - PLAYER_SERVICE_ADDR=playerservice:50051
      - CASE_SERVICE_ADDR=caseservice:50052
      - EVIDENCE_SERVICE_ADDR=evidenceservice:50053
      - INTERROGATION_SERVICE_ADDR=interrogationservice:50054
      - DEDUCTION_SERVICE_ADDR=deductionservice:50055
    depends_on:
      - player-service
      - case-service
      - evidence-service
      - interrogation-service
      - deduction-service

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=oda
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
