apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker/docker-compose.yaml convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: deduction-service
  name: deduction-service
spec:
  ports:
    - name: "50055"
      port: 50055
      targetPort: 50055
  selector:
    io.kompose.service: deduction-service
