apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker/docker-compose.yaml convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: game-service
  name: game-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: game-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f ../docker/docker-compose.yaml convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: game-service
    spec:
      containers:
        - env:
            - name: CASE_SERVICE_ADDR
              value: cases-ervice:50052
            - name: DEDUCTION_SERVICE_ADDR
              value: deduction-service:50055
            - name: EVIDENCE_SERVICE_ADDR
              value: evidence-service:50053
            - name: INTERROGATION_SERVICE_ADDR
              value: interrogation-service:50054
            - name: PLAYER_SERVICE_ADDR
              value: player-service:50051
            - name: CSI_SERVICE_ADDR
              value: csi-service:50057
          image: ghcr.io/vfiftyfive/oda-gameservicev2:latest
          name: game-service
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
