apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker/docker-compose.yaml convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: player-service
  name: player-service
spec:
  ports:
    - name: "50051"
      port: 50051
      targetPort: 50051
  selector:
    io.kompose.service: player-service
