apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker/docker-compose.yaml convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: player-service
  name: player-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: player-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f ../docker/docker-compose.yaml convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: player-service
    spec:
      containers:
        - command:
            - /app/wait-for-it.sh
            - db:5432
            - --
            - /app/playerservice
          env:
            - name: DATABASE_URL
              value: postgres://user:password@db:5432/oda
          image: ghcr.io/vfiftyfive/oda-playerservice:latest
          name: player-service
          ports:
            - containerPort: 50051
              protocol: TCP
      restartPolicy: Always
